apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: avocado-streaming
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

